package Brains2021.electronic.gradeBook.utils.enums;

public enum ESubjectName {
	SERBIAN_LANGUAGE_AND_LITERATURE, MATHEMATICS, ENGLISH_LANGUAGE, FINE_ART, MUSIC, PHYSICAL_EDUCATION,
	RELIGIOUS_EDUCATION, CIVICS, THE_WORLD_AROUND_US, FOREIGN_LANGUAGE, HISTORY, BIOLOGY, GEOGRAPHY, PHYSICS, CHEMISTRY,
	INFORMATION_TECHNOLOGY, TECHNICAL_SCIENCES
}
